"""add post and comment image url

Revision ID: 63c89e6a3c3b
Revises: 2babc17169af
Create Date: 2024-05-16 16:58:32.941387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c89e6a3c3b'
down_revision = '2babc17169af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
