"""fts5

Revision ID: d67a59cdc276
Revises: 8b2cb65c8247
Create Date: 2024-05-04 04:15:06.161688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67a59cdc276'
down_revision = '8b2cb65c8247'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        CREATE VIRTUAL TABLE IF NOT EXISTS search USING fts5(
            title,
            content
        );
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS search")
    # ### end Alembic commands ###
