"""add title fields in post model 

Revision ID: df53aa9d99e7
Revises: d67a59cdc276
Create Date: 2024-05-05 00:33:43.143171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df53aa9d99e7'
down_revision = 'd67a59cdc276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('title')

   
    # ### end Alembic commands ###
